### PR TITLE
Feature/53 save calculate results settings

### PR DESCRIPTION
**Pull request by cschwinderg**
## Related Issues:
* [TOTS-53](https://ergcloud.atlassian.net/browse/TOTS-53)

## Main Changes:
* Added calculate settings to the output of the publishing logic.
  * This involved making the settings on the calculate resources tab dependent on the selected sampling plan.

## Steps To Test:
1. Create a sampling plan
2. Add some samples to it
3. Create another sampling plan 
4. Add some samples to it
5. Go to the Calculate Resources tab
6. Change some of the settings
7. Go to Create Plan tab and back to Calculate Resources tab
8. Verify the settings you entered are still there
9. Switch to the other sampling plan you created
10. Verify the settings on the Calculate Resources tab are now the defaults
11. Change the settings on the Calculate Resources tab
12. Publish the output
13. In AGO, verify your calculate settings are in the feature service you just published
14. Back in TOTS, click "Start Over" on the "Create Plan" tab
15. From the "Add Data" tab, add in the layer you just published
16. Go to "Create Plan" tab and select the plan
17. Go to "Calculate Resources" 
18. Verify the settings match what was saved

### CODE REVIEW

**Review by ergjustin — APPROVED** [review]
@cschwinderg 
I followed the steps to test, everything works well. I have noticed that step 4 (Add some samples to it) an error occurring occasionally `Uncaught TypeError: Cannot read properties of null (reading 'add')`. For this error occurring I cannot be able to create sample.

**Comment by cschwinderg** [comment]
@ergjustin Can you send me a screenshot of the error? I wasn't able to reproduce it on my end.

**Comment by ergjustin** [comment]
Tots-39PR-4th-step

**Comment by cschwinderg** [comment]
Thank you. Hmm. Looks like it is coming from the Esri code. 

I'm going to go ahead and merge this in, since I'm still unable to reproduce it. 

I'll keep an eye out for it.

**Pull request merged**
